version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
   my-job:
      docker:
         - image: circleci/openjdk:15-jdk-buster
           auth:
             username: mydockerhub-user
             password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

workflows:
  my-workflow:
    jobs:
      - my-job
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results