version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:15-jdk-buster
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

jobs:
  my-job:
    executor: my-executor
    steps:
      - run: echo outside the executor
      - maven/test # checkout, build, test, and upload test results