version: 2.1
jobs:
  junit:
    docker:
      - image: circleci/openjdk:15-jdk-buster
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Java version
          command: java -version
      - run:
          name: Unit test
          command: mvn clean test

workflows:
  version: 2
  Test_Workflow:
    jobs:
      - junit