version: 2.1

orbs:
  maven: circleci/maven@0.0.12

commands: # a reusable command with parameters
   greeting:
      parameters:
         to:
           default: "world"
           type: string
      steps:
         - run: echo "Hello <<parameters.to>>"

jobs:
   my-job:
      docker:
         - image: circleci/openjdk:15-jdk-buster
           auth:
             username: mydockerhub-user
             password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
         - greeting:
           to: "AHOPACHE"

workflows:
  my-workflow:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - my-job #Config SDK